### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by DivyaAgarwal17** [MohamadMerchant/Voice-Authentication-and-Face-Recognition#13]
Hi, 
While running the code through command prompt(post including the env path in PATH variable) i am getting below error.
Could not import the PyAudio C module '_portaudio'.
Traceback (most recent call last):
  File "<path>/recognize.py", line 1, in <module>
    import pyaudio
  File "<path>\AppData\Local\Continuum\anaconda3\envs\Voice\lib\site-packages\pyaudio.py", line 116, in <module>
    import _portaudio as pa
ImportError: DLL load failed: The specified module could not be found.

python --version
Python 3.6.10 :: Anaconda

whereas this works fine using spyder in the same environment.Can you please suggest in this.

Thanks

**Comment by DivyaAgarwal17** [comment]
Solution : This works with python 3.6.8 instead of 3.6.10. On degrading the version it worked.
