### ISSUE TITLE
Error when execute add_user.py

### ISSUE THREAD

**Issue by rayyy424** [MohamadMerchant/Voice-Authentication-and-Face-Recognition#2]
Hi! Can you help me with this error? I found an error after running the file in anaconda prompt and I'm really don't get what is the error about.
Below is the error I get when I execute the command to run add_user.py,

(test) C:\Users\Rayyy\Downloads\Compressed\test>python add_user.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "add_user.py", line 10, in <module>
    from main_functions import *
  File "C:\Users\Rayyy\Downloads\Compressed\test\main_functions.py", line 10, in <module>
    np.set_printoptions(threshold=np.nan)
  File "D:\Anaconda\envs\test\lib\site-packages\numpy\core\arrayprint.py", line 247, in set_printoptions
    floatmode, legacy)
  File "D:\Anaconda\envs\test\lib\site-packages\numpy\core\arrayprint.py", line 93, in _make_options_dict
    raise ValueError("threshold must be numeric and non-NAN, try "
ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

**Comment by Ealuthwala** [comment]
this one is pretty simple.. just chance the line 10 in main_functions.py to 
np.set_printoptions(threshold=sys.maxsize) and import sys
